import { validateSql } from './validation';

/**
 * AI Query Copilot backend (§2.3, §5).
 *
 * Calls any OpenAI-compatible chat-completions endpoint (configure via
 * AI_BASE_URL / AI_API_KEY / AI_MODEL — e.g. an open-weight code model on a
 * low-cost inference provider, or a local Ollama). The key never reaches the
 * browser; this module is only imported from Route Handlers.
 *
 * When no provider is configured, a deterministic rule-based fallback keeps
 * the sidebar useful offline (explain/review from the static linter).
 */

export type AiMode = 'edit' | 'explain' | 'review';

const SYSTEM_PROMPT = `You are the M.Design Query Dictionary copilot, assisting Oracle support engineers with SQL and PL/SQL.

Hard rules (behavior contract):
- You have NO access to any database, schema, or live data. Never assert that a table, column, or row count exists. If asked, say: "I can't check the live schema — this is based on the query text only."
- You only work with the single query the user has open.
- For EDIT requests: reply with a short explanation of what you changed and why (mapping each part of the request to the change), then EXACTLY ONE fenced sql code block containing the COMPLETE revised query. No other code blocks.
- If a requested change would remove a WHERE clause from an UPDATE/DELETE, or turn a SELECT into a DML statement, start your reply with the line "⚠ RISK ESCALATION:" and explain the blast radius before the code block.
- For EXPLAIN requests: plain-language breakdown — what it does, tables/joins referenced (as written in the text), parameters, and side effects (especially DML). No code block needed.
- For REVIEW requests: list concrete best-practice findings from the text alone (SELECT *, missing binds, implicit conversion risks, missing exception handling), each with a short fix suggestion.
- Target dialect is Oracle SQL / PL/SQL. Prefer bind variables (:name) over literals.`;

export function providerConfigured(): boolean {
  return !!process.env.AI_BASE_URL;
}

// Groq rejects `reasoning_format` outright (400) for models that don't
// support it — it's not a universally-ignored param like on most
// OpenAI-compatible providers, so only send it for Groq's actual reasoning
// models (the documented default, llama-3.3-70b-versatile, isn't one).
const GROQ_REASONING_MODEL = /deepseek-r1|qwq|gpt-oss/i;

export async function streamChat(mode: AiMode, queryBody: string, instruction: string): Promise<ReadableStream<Uint8Array>> {
  const base = process.env.AI_BASE_URL!;
  const model = process.env.AI_MODEL ?? 'llama-3.3-70b-versatile';
  const res = await fetch(`${base.replace(/\/$/, '')}/chat/completions`, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      ...(process.env.AI_API_KEY ? { authorization: `Bearer ${process.env.AI_API_KEY}` } : {}),
    },
    body: JSON.stringify({
      model,
      stream: true,
      temperature: 0.2,
      // Groq: keep reasoning-model think-traces out of the content stream (ignored by other providers)
      ...(base.includes('groq.com') && GROQ_REASONING_MODEL.test(model) ? { reasoning_format: 'hidden' } : {}),
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        {
          role: 'user',
          content: `Mode: ${mode.toUpperCase()}\n\nCurrent query:\n\`\`\`sql\n${queryBody}\n\`\`\`\n\nRequest: ${instruction || '(none — apply the mode)'}`,
        },
      ],
    }),
  });
  if (!res.ok || !res.body) {
    const text = await res.text().catch(() => '');
    throw new Error(`AI provider returned ${res.status}: ${text.slice(0, 300)}`);
  }

  // Re-emit as plain text tokens (strip SSE/JSON framing here, server-side)
  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  const encoder = new TextEncoder();
  let buf = '';
  return new ReadableStream<Uint8Array>({
    async pull(controller) {
      const { done, value } = await reader.read();
      if (done) {
        controller.close();
        return;
      }
      buf += decoder.decode(value, { stream: true });
      const lines = buf.split('\n');
      buf = lines.pop() ?? '';
      for (const line of lines) {
        const data = line.replace(/^data:\s*/, '').trim();
        if (!data || data === '[DONE]') continue;
        try {
          const parsed = JSON.parse(data);
          const token = parsed.choices?.[0]?.delta?.content ?? '';
          if (token) controller.enqueue(encoder.encode(token));
        } catch {
          /* partial frame — wait for more */
        }
      }
    },
    cancel() {
      reader.cancel();
    },
  });
}

/** Offline fallback: deterministic output derived from the static linter. */
export function fallbackResponse(mode: AiMode, queryBody: string, instruction: string): string {
  const v = validateSql(queryBody);
  const kinds = v.statement_kinds.join(', ') || 'none';
  if (mode === 'explain') {
    const lines = [
      `**Offline explanation** (no AI provider configured — this is generated by the static analyzer):`,
      ``,
      `- Statement type(s): ${kinds}`,
      `- Computed risk level: ${v.risk_level.replace('_', ' ')}`,
      v.findings.length
        ? `- Analyzer notes:\n${v.findings.map((f) => `  - [${f.severity}] line ${f.line}: ${f.message}`).join('\n')}`
        : `- No analyzer findings.`,
      ``,
      `I can't check any live schema — this is based on the query text only. Configure AI_BASE_URL / AI_API_KEY / AI_MODEL in docker-compose.yml to enable full natural-language assistance.`,
    ];
    return lines.join('\n');
  }
  if (mode === 'review') {
    const notes = v.findings.filter((f) => f.severity !== 'error');
    return [
      `**Offline best-practice review** (static analyzer only — no AI provider configured):`,
      ``,
      notes.length
        ? notes.map((f) => `- [${f.severity}] line ${f.line}: ${f.message} (${f.code})`).join('\n')
        : '- No findings from the static rules. Configure an AI provider for deeper text-based review.',
      ``,
      `Reminder: no live schema access exists anywhere in this platform — findings are text-based only.`,
    ].join('\n');
  }
  return [
    `**AI editing is unavailable offline.** No AI provider is configured (AI_BASE_URL is unset), and rule-based editing would risk silently misinterpreting "${instruction}".`,
    ``,
    `To enable the copilot, set AI_BASE_URL / AI_API_KEY / AI_MODEL in docker-compose.yml — any OpenAI-compatible endpoint serving an open-weight SQL-capable model works (Groq, Together, local Ollama, ...).`,
    ``,
    `The static validation results below the editor still apply to manual edits.`,
  ].join('\n');
}
